#!/bin/bash

echo "🔍 Diagnóstico e Correção de DNS na GoDaddy"
echo "=========================================="
echo ""
echo "PROBLEMA: Domínio resolvendo para IPs do Cloudflare sem você ter cadastrado."
echo ""

echo "📋 Status Atual do DNS:"
echo "----------------------"
nslookup theshelter.foundation

echo ""
echo "🔍 Análise:"
echo "----------"
echo "IPs encontrados:"
echo "  1. 76.223.105.230  → Cloudflare IP"
echo "  2. 13.248.243.5    → Cloudflare IP" 
echo "  3. 85.31.239.235   → SEU VPS (correto)"
echo ""
echo "⚠️  O domínio tem MÚLTIPLOS registros A na GoDaddy."
echo ""

echo "🚀 SOLUÇÃO: Remover IPs do Cloudflare da GoDaddy"
echo "-----------------------------------------------"
echo ""
echo "PASSO 1: Acesse a GoDaddy"
echo "  URL: https://godaddy.com"
echo "  Faça login na sua conta"
echo ""
echo "PASSO 2: Vá para Gerenciamento de DNS"
echo "  1. Clique em 'Domínios'"
echo "  2. Clique em 'theshelter.foundation'"
echo "  3. Clique em 'Gerenciar DNS'"
echo ""
echo "PASSO 3: Remova registros A incorretos"
echo "  Na seção 'Registros', procure por:"
echo "  - Tipo: A"
echo "  - Host: @"
echo "  - Aponta para: 76.223.105.230  → REMOVER"
echo "  - Aponta para: 13.248.243.5    → REMOVER"
echo ""
echo "  DEIXE APENAS:"
echo "  - Tipo: A"
echo "  - Host: @"
echo "  - Aponta para: 85.31.239.235   → MANTER"
echo ""
echo "PASSO 4: Verifique registro CNAME"
echo "  - Tipo: CNAME"
echo "  - Host: www"
echo "  - Aponta para: theshelter.foundation → DEVE ESTAR ASSIM"
echo ""
echo "PASSO 5: Salve as alterações"
echo ""
echo "⏱️  Propagação DNS:"
echo "  - Alterações imediatas na GoDaddy"
echo "  - Propagação global: 1-2 horas"
echo "  - Máximo: 24 horas"
echo ""

echo "✅ Verificação Pós-Correção:"
echo "---------------------------"
echo "Após salvar, aguarde 30 minutos e execute:"
echo "nslookup theshelter.foundation"
echo ""
echo "Deve mostrar APENAS: 85.31.239.235"
echo ""

echo "🔐 Configuração de SSL (APÓS DNS CORRETO):"
echo "-----------------------------------------"
echo "Quando o DNS estiver correto (apenas 85.31.239.235):"
echo ""
echo "1. No VPS, execute:"
echo "   sudo certbot --nginx -d theshelter.foundation -d www.theshelter.foundation"
echo ""
echo "2. Siga as instruções interativas"
echo "3. Escolha 'Redirect' para HTTP→HTTPS"
echo ""

echo "📞 Verificações Importantes:"
echo "---------------------------"
echo "1. Teste local no VPS:"
echo "   curl -H 'Host: theshelter.foundation' http://localhost"
echo ""
echo "2. Teste DNS em diferentes locais:"
echo "   https://www.whatsmydns.net/#A/theshelter.foundation"
echo ""
echo "3. Verifique logs do Nginx:"
echo "   sudo tail -f /var/log/nginx/theshelter.error.log"
echo ""

echo "🎯 RESUMO DA SITUAÇÃO:"
echo "---------------------"
echo "✅ SEU VPS: 85.31.239.235 (correto)"
echo "❌ CLOUDFARE IPs: 76.223.105.230, 13.248.243.5 (incorreto - remover)"
echo "🔧 AÇÃO: Remova os IPs do Cloudflare da GoDaddy"
echo "⏱️  PRAZO: 1-2 horas para propagação"
echo "🔐 SSL: Configurável após DNS correto"
echo ""

echo "💡 Dica: Se não conseguir acessar a GoDaddy ou não encontrar os registros,"
echo "entre em contato com o suporte da GoDaddy informando que há registros A"
echo "incorretos no domínio theshelter.foundation."